#index:
#    path: /
#    controller: App\Controller\DefaultController::index

utilisateur_creation:
    path:     /PFR-MADERA/utilisateur/
    defaults: { _controller: 'App\Controller\UtilisateurController::creationUtilisateur' }
    methods:  POST

utilisateur_detail:
    path:     /PFR-MADERA/utilisateur/
    defaults: { _controller: 'App\Controller\UtilisateurController::affichageUtilisateur' }
    methods:  GET

utilisateur_liste:
    path:     /PFR-MADERA/utilisateur/liste/
    defaults: { _controller: 'App\Controller\UtilisateurController::listeUtilisateur' }
    methods:  GET

utilisateur_devis:
    path:     /PFR-MADERA/utilisateur/devis/
    defaults: { _controller: 'App\Controller\UtilisateurController::devisUtilisateur' }
    methods:  GET

utilisateur_modification:
    path:     /PFR-MADERA/utilisateur/
    defaults: { _controller: 'App\Controller\UtilisateurController::modificationUtilisateur' }
    methods:  PUT

utilisateur_suppression:
    path:     /PFR-MADERA/utilisateur/
    defaults: { _controller: 'App\Controller\UtilisateurController::suppressionUtilisateur' }
    methods:  DELETE

gamme_liste:
    path:     /PFR-MADERA/gamme/liste/
    defaults: { _controller: 'App\Controller\GammeController::listeGamme' }
    methods:  GET

gamme_modules:
    path:     /PFR-MADERA/gamme/modules/
    defaults: { _controller: 'App\Controller\GammeController::listeModules' }
    methods:  GET

devis_creation:
    path:     /PFR-MADERA/devis/
    defaults: { _controller: 'App\Controller\DevisController::creationDevis' }
    methods:  POST