#index:
#    path: /
#    controller: App\Controller\DefaultController::index

client_creation:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::creationClient' }
    methods:  POST

client_affichage:
    path:     /PFR-MADERA/client/{id}
    defaults: { _controller: 'App\Controller\ClientController::affichageClient' }
    methods:  GET

client_modification:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::modificationClient' }
    methods:  PUT

client_suppression:
    path:     /PFR-MADERA/client/{id}
    defaults: { _controller: 'App\Controller\ClientController::suppressionClient' }
    methods:  DELETE

client_liste:
    path:     /PFR-MADERA/clients
    defaults: { _controller: 'App\Controller\ClientController::listeClient' }
    methods:  GET

client_count:
    path:     /PFR-MADERA/clients/count
    defaults: { _controller: 'App\Controller\ClientController::countClient' }
    methods:  GET

client_recherche:
    path:     /PFR-MADERA/client/recherche/{recherche}
    defaults: { _controller: 'App\Controller\ClientController::rechercheClient' }
    methods:  GET

commercial_creation:
    path:     /PFR-MADERA/commercial
    defaults: { _controller: 'App\Controller\CommercialController::creationCommercial' }
    methods:  POST

commercial_affichage:
    path:     /PFR-MADERA/commercial/{id}
    defaults: { _controller: 'App\Controller\CommercialController::affichageCommercial' }
    methods:  GET

commercial_count:
    path:     /PFR-MADERA/commercials/count
    defaults: { _controller: 'App\Controller\CommercialController::countCommercial' }
    methods:  GET

commercial_modification:
    path:     /PFR-MADERA/commercial
    defaults: { _controller: 'App\Controller\CommercialController::modificationCommercial' }
    methods:  PUT

commercial_suppression:
    path:     /PFR-MADERA/commercial/{id}
    defaults: { _controller: 'App\Controller\CommercialController::suppressionCommercial' }
    methods:  DELETE

commercial_liste:
    path:     /PFR-MADERA/commercials
    defaults: { _controller: 'App\Controller\CommercialController::listeCommercial' }
    methods:  GET

commercial_login:
    path:     /PFR-MADERA/commercial/login
    defaults: { _controller: 'App\Controller\CommercialController::loginCommercial' }
    methods:  POST

devis_creation:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::creationDevis' }
    methods:  POST

devis_affichage:
    path:     /PFR-MADERA/devis/{id}
    defaults: { _controller: 'App\Controller\DevisController::affichageDevis' }
    methods:  GET
 
devis_modification:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::modificationDevis' }
    methods:  PUT

devis_suppression:
    path:     /PFR-MADERA/devis/{id}
    defaults: { _controller: 'App\Controller\DevisController::suppressionDevis' }
    methods:  DELETE

devis_liste:
    path:     /PFR-MADERA/deviss
    defaults: { _controller: 'App\Controller\DevisController::listeDevis' }
    methods:  GET

deviss_count:
    path:     /PFR-MADERA/deviss/count
    defaults: { _controller: 'App\Controller\DevisController::countDevis' }
    methods:  GET

devis_listeDuClient:
    path:     /PFR-MADERA/devis/listeDuClient
    defaults: { _controller: 'App\Controller\DevisController::listeDuClient' }
    methods:  GET

pays_liste:
    path:     /PFR-MADERA/pays/liste
    defaults: { _controller: 'App\Controller\PaysController::listePays' }
    methods:  GET

finitionExterieur_liste:
    path:     /PFR-MADERA/finitionExterieur/liste
    defaults: { _controller: 'App\Controller\FinitionExterieurController::listeFinitionExterieur' }
    methods:  GET

finitionInterieur_liste:
    path:     /PFR-MADERA/finitionInterieur/liste
    defaults: { _controller: 'App\Controller\FinitionInterieurController::listeFinitionInterieur' }
    methods:  GET

isolant_liste:
    path:     /PFR-MADERA/isolant/liste
    defaults: { _controller: 'App\Controller\IsolantController::listeIsolant' }
    methods:  GET

huisseries_liste:
    path:     /PFR-MADERA/huisseries/liste
    defaults: { _controller: 'App\Controller\HuisseriesController::listeHuisseries' }
    methods:  GET

maison_liste:
    path:     /PFR-MADERA/maison/liste
    defaults: { _controller: 'App\Controller\MaisonController::listeMaison' }
    methods:  GET

cctp_liste:
    path:     /PFR-MADERA/cctp/liste
    defaults: { _controller: 'App\Controller\CCTPController::listeCCTP' }
    methods:  GET

couverture_liste:
    path:     /PFR-MADERA/couverture/liste
    defaults: { _controller: 'App\Controller\CouvertureController::listeCouverture' }
    methods:  GET

caracteristique_creation:
    path:     /PFR-MADERA/caracteristique
    defaults: { _controller: 'App\Controller\CaracteristiqueController::creationCaracteristique' }
    methods:  POST

caracteristique_affichage:
    path:     /PFR-MADERA/caracteristique/{id}
    defaults: { _controller: 'App\Controller\CaracteristiqueController::affichageCaracteristique' }
    methods:  GET

caracteristique_modification:
    path:     /PFR-MADERA/caracteristique
    defaults: { _controller: 'App\Controller\CaracteristiqueController::modificationCaracteristique' }
    methods:  PUT

caracteristique_suppression:
    path:     /PFR-MADERA/caracteristique/{id}
    defaults: { _controller: 'App\Controller\CaracteristiqueController::suppressionCaracteristique' }
    methods:  DELETE

caracteristique_liste_module:
    path:     /PFR-MADERA/caracteristique/liste/module/{id}
    defaults: { _controller: 'App\Controller\CaracteristiqueController::listeCaracteristiqueModule' }
    methods:  GET

caracteristique_liste_modules_count:
    path:     /PFR-MADERA/caracteristique/liste/module/{id}/count
    defaults: { _controller: 'App\Controller\CaracteristiqueController::countListeCaracteristiqueModule' }
    methods:  GET

gamme_liste:
    path:     /PFR-MADERA/gamme/liste
    defaults: { _controller: 'App\Controller\GammeController::listeGamme' }
    methods:  GET

security_login:
    path:     /PFR-MADERA/login
    defaults: { _controller: 'App\Controller\SecurityController::login' }
    methods:  POST

security_logout:
    path:     /PFR-MADERA/logout
    defaults: { _controller: 'App\Controller\SecurityController::logout' }
    methods:  POST

module_creation:
     path:     /PFR-MADERA/module
     defaults: { _controller: 'App\Controller\ModuleController::creationModule' }
     methods:  POST

module_affichage:
    path:     /PFR-MADERA/module/{id}
    defaults: { _controller: 'App\Controller\ModuleController::affichageModule' }
    methods:  GET

module_modification:
    path:     /PFR-MADERA/module
    defaults: { _controller: 'App\Controller\ModuleController::modificationModule' }
    methods:  PUT

module_suppression:
    path:     /PFR-MADERA/module/{id}
    defaults: { _controller: 'App\Controller\ModuleController::suppressionModule' }
    methods:  DELETE

module_liste:
    path:     /PFR-MADERA/modules
    defaults: { _controller: 'App\Controller\ModuleController::listeModule' }
    methods:  GET

module_liste_gamme_type:
    path:     /PFR-MADERA/module/liste/gamme/{gamm_id}/type/{tymo_id}
    defaults: { _controller: 'App\Controller\ModuleController::listeModuleGammeType' }
    methods:  GET

module_liste_devis:
    path:     /PFR-MADERA/module/liste/devis/{id}
    defaults: { _controller: 'App\Controller\ModuleController::listeModuleDevis' }
    methods:  GET

module_liste_devis_count:
    path:     /PFR-MADERA/module/liste/devis/{id}/count
    defaults: { _controller: 'App\Controller\ModuleController::countListeModuleDevis' }
    methods:  GET

type_module_liste:
    path:     /PFR-MADERA/type_module/liste
    defaults: { _controller: 'App\Controller\TypeModuleController::listeTypeModule' }
    methods:  GET

devis_generation_dossier_estimatif:
    path:     /PFR-MADERA/devis/dossier_estimatif/{id}
    defaults: { _controller: 'App\Controller\DevisController::generationDossierEstimatif' }
    methods:  GET

devis_generation_dossier_technique:
    path:     /PFR-MADERA/devis/dossier_technique/{id}
    defaults: { _controller: 'App\Controller\DevisController::generationDossierTechnique' }
    methods:  GET

etape_liste:
    path:     /PFR-MADERA/etapes
    defaults: { _controller: 'App\Controller\EtapeController::listeEtape' }
    methods:  GET

etat_liste:
    path:     /PFR-MADERA/etats
    defaults: { _controller: 'App\Controller\EtatController::listeEtat' }
    methods:  GET

# gamme_modules:
#     path:     /PFR-MADERA/gamme/modules/
#     defaults: { _controller: 'App\Controller\GammeController::listeModules' }
#     methods:  GET
