#index:
#    path: /
#    controller: App\Controller\DefaultController::index

pays_liste:
    path:     /PFR-MADERA/pays/liste
    defaults: { _controller: 'App\Controller\PaysController::listePays' }
    methods:  GET

client_creation:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::creationClient' }
    methods:  POST

client_affichage:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::affichageClient' }
    methods:  GET

client_modification:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::modificationClient' }
    methods:  PUT

client_suppression:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::suppressionClient' }
    methods:  DELETE

client_liste:
    path:     /PFR-MADERA/client/liste/
    defaults: { _controller: 'App\Controller\ClientController::listeClient' }
    methods:  GET

client_recherche:
    path:     /PFR-MADERA/client/recherche
    defaults: { _controller: 'App\Controller\ClientController::rechercheClient' }
    methods:  GET

gamme_liste:
    path:     /PFR-MADERA/gamme/liste
    defaults: { _controller: 'App\Controller\GammeController::listeGamme' }
    methods:  GET

# gamme_modules:
#     path:     /PFR-MADERA/gamme/modules/
#     defaults: { _controller: 'App\Controller\GammeController::listeModules' }
#     methods:  GET

# devis_creation:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::creationDevis' }
#     methods:  POST

# devis_affichage:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::affichageDevis' }
#     methods:  GET
 
# devis_modification:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::modificationDevis' }
#     methods:  PUT

devis_suppression:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::suppressionDevis' }
    methods:  DELETE

devis_liste:
    path:     /PFR-MADERA/devis/liste
    defaults: { _controller: 'App\Controller\DevisController::listeDevis' }
    methods:  GET

devis_listeDuClient:
    path:     /PFR-MADERA/devis/listeDuClient
    defaults: { _controller: 'App\Controller\DevisController::listeDuClient' }
    methods:  GET

finitionExterieur_liste:
    path:     /PFR-MADERA/finitionExterieur/liste
    defaults: { _controller: 'App\Controller\FinitionExterieurController::listeFinitionExterieur' }
    methods:  GET

finitionInterieur_liste:
    path:     /PFR-MADERA/finitionInterieur/liste
    defaults: { _controller: 'App\Controller\FinitionInterieurController::listeFinitionInterieur' }
    methods:  GET

isolant_liste:
    path:     /PFR-MADERA/isolant/liste
    defaults: { _controller: 'App\Controller\IsolantController::listeIsolant' }
    methods:  GET

huisseries_liste:
    path:     /PFR-MADERA/huisseries/liste
    defaults: { _controller: 'App\Controller\HuisseriesController::listeHuisseries' }
    methods:  GET

maison_liste:
    path:     /PFR-MADERA/maison/liste
    defaults: { _controller: 'App\Controller\MaisonController::listeMaison' }
    methods:  GET

cctp_liste:
    path:     /PFR-MADERA/cctp/liste
    defaults: { _controller: 'App\Controller\CCTPController::listeCCTP' }
    methods:  GET

couverture_liste:
    path:     /PFR-MADERA/couverture/liste
    defaults: { _controller: 'App\Controller\CouvertureController::listeCouverture' }
    methods:  GET

caracteristique_liste:
    path:     /PFR-MADERA/caracteristique/liste
    defaults: { _controller: 'App\Controller\CaracteristiqueController::listeCaracteristique' }
    methods:  GET