#index:
#    path: /
#    controller: App\Controller\DefaultController::index

client_creation:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::creationClient' }
    methods:  POST

client_affichage:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::affichageClient' }
    methods:  GET

pays_liste:
    path:     /PFR-MADERA/pays/liste
    defaults: { _controller: 'App\Controller\PaysController::listePays' }
    methods:  GET

client_liste:
    path:     /PFR-MADERA/client/liste/
    defaults: { _controller: 'App\Controller\ClientController::listeClient' }
    methods:  GET

# utilisateur_devis:
#     path:     /PFR-MADERA/utilisateur/devis/
#     defaults: { _controller: 'App\Controller\UtilisateurController::devisUtilisateur' }
#     methods:  GET

client_recherche:
    path:     /PFR-MADERA/client/recherche
    defaults: { _controller: 'App\Controller\ClientController::rechercheClient' }
    methods:  GET

# utilisateur_modification:
#     path:     /PFR-MADERA/utilisateur/
#     defaults: { _controller: 'App\Controller\UtilisateurController::modificationUtilisateur' }
#     methods:  PUT

client_suppression:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::suppressionClient' }
    methods:  DELETE

# gamme_liste:
#     path:     /PFR-MADERA/gamme/liste/
#     defaults: { _controller: 'App\Controller\GammeController::listeGamme' }
#     methods:  GET

# gamme_modules:
#     path:     /PFR-MADERA/gamme/modules/
#     defaults: { _controller: 'App\Controller\GammeController::listeModules' }
#     methods:  GET

# devis_creation:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::creationDevis' }
#     methods:  POST

# devis_affichage:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::affichageDevis' }
#     methods:  GET
 
# devis_modification:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::modificationDevis' }
#     methods:  PUT

# devis_suppression:
#     path:     /PFR-MADERA/devis/
#     defaults: { _controller: 'App\Controller\DevisController::suppressionDevis' }
#     methods:  DELETE

# devis_liste:
#     path:     /PFR-MADERA/devis/liste/
#     defaults: { _controller: 'App\Controller\DevisController::listeDevis' }
#     methods:  GET

finitionExterieur_liste:
    path:     /PFR-MADERA/finitionExterieur/liste
    defaults: { _controller: 'App\Controller\FinitionExterieurController::listeFinitionExterieur' }
    methods:  GET

finitionInterieur_liste:
    path:     /PFR-MADERA/finitionInterieur/liste
    defaults: { _controller: 'App\Controller\FinitionInterieurController::listeFinitionInterieur' }
    methods:  GET