#index:
#    path: /
#    controller: App\Controller\DefaultController::index


client_creation:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::creationClient' }
    methods:  POST

client_affichage:
    path:     /PFR-MADERA/client/{id}
    defaults: { _controller: 'App\Controller\ClientController::affichageClient' }
    methods:  GET

client_modification:
    path:     /PFR-MADERA/client
    defaults: { _controller: 'App\Controller\ClientController::modificationClient' }
    methods:  PUT

client_suppression:
    path:     /PFR-MADERA/client/{id}
    defaults: { _controller: 'App\Controller\ClientController::suppressionClient' }
    methods:  DELETE

client_liste:
    path:     /PFR-MADERA/clients
    defaults: { _controller: 'App\Controller\ClientController::listeClient' }
    methods:  GET

client_recherche:
    path:     /PFR-MADERA/client/recherche
    defaults: { _controller: 'App\Controller\ClientController::rechercheClient' }
    methods:  GET

commercial_creation:
    path:     /PFR-MADERA/commercial
    defaults: { _controller: 'App\Controller\CommercialController::creationCommercial' }
    methods:  POST

commercial_affichage:
    path:     /PFR-MADERA/commercial/{id}
    defaults: { _controller: 'App\Controller\CommercialController::affichageCommercial' }
    methods:  GET

commercial_count:
    path:     /PFR-MADERA/commercial/count
    defaults: { _controller: 'App\Controller\CommercialController::countCommercial' }
    methods:  GET

commercial_modification:
    path:     /PFR-MADERA/commercial
    defaults: { _controller: 'App\Controller\CommercialController::modificationCommercial' }
    methods:  PUT

commercial_suppression:
    path:     /PFR-MADERA/commercial/{id}
    defaults: { _controller: 'App\Controller\CommercialController::suppressionCommercial' }
    methods:  DELETE

commercial_liste:
    path:     /PFR-MADERA/commercial
    defaults: { _controller: 'App\Controller\CommercialController::listeCommercial' }
    methods:  GET

commercial_login:
    path:     /PFR-MADERA/commercial/login
    defaults: { _controller: 'App\Controller\CommercialController::loginCommercial' }
    methods:  POST

devis_creation:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::creationDevis' }
    methods:  POST

devis_affichage:
    path:     /PFR-MADERA/devis/{id}
    defaults: { _controller: 'App\Controller\DevisController::affichageDevis' }
    methods:  GET
 
devis_modification:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::modificationDevis' }
    methods:  PUT

devis_suppression:
    path:     /PFR-MADERA/devis
    defaults: { _controller: 'App\Controller\DevisController::suppressionDevis' }
    methods:  DELETE

devis_liste:
    path:     /PFR-MADERA/deviss
    defaults: { _controller: 'App\Controller\DevisController::listeDevis' }
    methods:  GET

devis_listeDuClient:
    path:     /PFR-MADERA/devis/listeDuClient
    defaults: { _controller: 'App\Controller\DevisController::listeDuClient' }
    methods:  GET

pays_liste:
    path:     /PFR-MADERA/pays/liste
    defaults: { _controller: 'App\Controller\PaysController::listePays' }
    methods:  GET

finitionExterieur_liste:
    path:     /PFR-MADERA/finitionExterieur/liste
    defaults: { _controller: 'App\Controller\FinitionExterieurController::listeFinitionExterieur' }
    methods:  GET

finitionInterieur_liste:
    path:     /PFR-MADERA/finitionInterieur/liste
    defaults: { _controller: 'App\Controller\FinitionInterieurController::listeFinitionInterieur' }
    methods:  GET

isolant_liste:
    path:     /PFR-MADERA/isolant/liste
    defaults: { _controller: 'App\Controller\IsolantController::listeIsolant' }
    methods:  GET

huisseries_liste:
    path:     /PFR-MADERA/huisseries/liste
    defaults: { _controller: 'App\Controller\HuisseriesController::listeHuisseries' }
    methods:  GET

maison_liste:
    path:     /PFR-MADERA/maison/liste
    defaults: { _controller: 'App\Controller\MaisonController::listeMaison' }
    methods:  GET

cctp_liste:
    path:     /PFR-MADERA/cctp/liste
    defaults: { _controller: 'App\Controller\CCTPController::listeCCTP' }
    methods:  GET

couverture_liste:
    path:     /PFR-MADERA/couverture/liste
    defaults: { _controller: 'App\Controller\CouvertureController::listeCouverture' }
    methods:  GET

caracteristique_liste:
    path:     /PFR-MADERA/caracteristique/liste
    defaults: { _controller: 'App\Controller\CaracteristiqueController::listeCaracteristique' }
    methods:  GET

gamme_liste:
    path:     /PFR-MADERA/gamme/liste
    defaults: { _controller: 'App\Controller\GammeController::listeGamme' }
    methods:  GET

security_login:
    path:     /PFR-MADERA/login
    defaults: { _controller: 'App\Controller\SecurityController::login' }
    methods:  POST

security_logout:
    path:     /PFR-MADERA/logout
    defaults: { _controller: 'App\Controller\SecurityController::logout' }
    methods:  POST

module_creation:
     path:     /PFR-MADERA/module
     defaults: { _controller: 'App\Controller\ModuleController::creationModule' }
     methods:  POST

module_affichage:
    path:     /PFR-MADERA/module/{id}
    defaults: { _controller: 'App\Controller\ModuleController::affichageModule' }
    methods:  GET

module_modification:
    path:     /PFR-MADERA/module
    defaults: { _controller: 'App\Controller\ModuleController::modificationModule' }
    methods:  PUT

module_suppression:
    path:     /PFR-MADERA/module/{id}
    defaults: { _controller: 'App\Controller\ModuleController::suppressionModule' }
    methods:  DELETE

module_liste:
    path:     /PFR-MADERA/module
    defaults: { _controller: 'App\Controller\ModuleController::listeModule' }
    methods:  GET

module_liste_gamme:
    path:     /PFR-MADERA/module/liste/gamme
    defaults: { _controller: 'App\Controller\ModuleController::listeModuleGamme' }
    methods:  GET

module_liste_devis:
    path:     /PFR-MADERA/module/liste/devis
    defaults: { _controller: 'App\Controller\ModuleController::listeModuleDevis' }
    methods:  GET

# gamme_modules:
#     path:     /PFR-MADERA/gamme/modules/
#     defaults: { _controller: 'App\Controller\GammeController::listeModules' }
#     methods:  GET
