#index:
#    path: /
#    controller: App\Controller\DefaultController::index

utilisateur_creation:
    path:     /PFR-MADERA/utilisateur/
    defaults: { _controller: 'App\Controller\UtilisateurController::creationUtilisateur' }
    methods:  POST


#utilisateur_debis:
#    path:     /PFR-MADERA/utilisateur/devis/
#    defaults: { _controller: 'App\Controller\UtilisateurController::listeDevis' }
#    methods:  GET